# Generated by Django 3.1.7 on 2021-04-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_exercise_parts_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='owner',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
