# Generated by Django 3.1.7 on 2021-04-08 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210404_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 19, 0), verbose_name='Date and Time of Workout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='journal',
            field=models.CharField(max_length=200, null=True, verbose_name='Post-Workout Thoughts'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='points_earned',
            field=models.PositiveIntegerField(default=5, verbose_name='Points from Workout'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Length of Workout (in minutes)'),
        ),
    ]
