# Generated by Django 3.1.7 on 2021-04-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210407_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='journal',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
