# Generated by Django 3.1.7 on 2021-04-01 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_exercise_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='parts_worked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
    ]
