# Generated by Django 3.1.5 on 2021-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20210319_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Date and Time of Workout')),
                ('exercise_type', models.CharField(choices=[(1, 'Balance'), (2, 'Cardio'), (3, 'Flexibility'), (4, 'Strength'), (5, 'Other')], default=1, max_length=15)),
                ('body_part_exercised', models.CharField(choices=[(1, 'Abdominals'), (2, 'Arms'), (3, 'Back'), (4, 'Chest'), (5, 'Legs'), (6, 'Shoulders'), (7, 'Other')], default=1, max_length=15)),
                ('exercise_intensity', models.CharField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Vigorous')], default=1, max_length=15)),
                ('time', models.PositiveSmallIntegerField(null=True, verbose_name='Length of Workout (in minutes)')),
                ('journal', models.CharField(max_length=200, null=True, verbose_name='Post-Workout Thoughts')),
                ('points_earned', models.PositiveIntegerField(default=5, verbose_name='Points from Workout')),
            ],
        ),
    ]
