# Generated by Django 3.1.7 on 2021-04-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20210404_1107'),
        ('oauth', '0005_delete_exercise'),
    ]

    operations = [
    ]
