# Generated by Django 3.1.7 on 2021-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_merge_20210404_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos/', verbose_name='Profile picure'),
        ),
    ]
